language: scala

jobs:
  include:
    - script: sbt ++$TRAVIS_SCALA_VERSION test
      scala:
        - 2.11.11
        - 2.12.8
    - stage: docs
      script: sbt ++$TRAVIS_SCALA_VERSION tut
      scala:
        - 2.11.11
        - 2.12.8
